import type { TournamentFormatPreset } from "@/lib/types";

export const formatPresets: TournamentFormatPreset[] = [
  {
    id: "swiftplay-bo3",
    name: "速战速决",
    teamCount: 2,
    minMinutes: 25,
    maxMinutes: 50,
    fairness: 6,
    fun: 8,
    seriousnessFit: { serious: 4, balanced: 7, fun: 8 },
    summary: "三把 Swiftplay 快速轮换，适合工作日晚间的紧凑对局。",
    matchCount: 3,
  },
  {
    id: "standard-bo3",
    name: "标准夜赛",
    teamCount: 2,
    minMinutes: 60,
    maxMinutes: 120,
    fairness: 10,
    fun: 7,
    seriousnessFit: { serious: 10, balanced: 8, fun: 5 },
    summary: "最稳妥的正式模式，保留完整 BO3 节奏和地图 veto 仪式感。",
    matchCount: 3,
  },
  {
    id: "championship-bo5",
    name: "决赛夜",
    teamCount: 2,
    minMinutes: 140,
    maxMinutes: 240,
    fairness: 10,
    fun: 9,
    seriousnessFit: { serious: 9, balanced: 8, fun: 6 },
    summary: "BO5 配合中场环节、MVP 投票和总决赛包装。",
    matchCount: 5,
  },
  {
    id: "tri-finals",
    name: "三队循环 + 总决赛",
    teamCount: 3,
    minMinutes: 90,
    maxMinutes: 160,
    fairness: 10,
    fun: 9,
    seriousnessFit: { serious: 8, balanced: 10, fun: 8 },
    summary: "三队先打循环积分，再由前二进入总决赛，是当前唐氏杯 3 队默认模式。",
    matchCount: 4,
  },
  {
    id: "triple-round-robin",
    name: "三强循环",
    teamCount: 3,
    minMinutes: 75,
    maxMinutes: 140,
    fairness: 10,
    fun: 8,
    seriousnessFit: { serious: 8, balanced: 10, fun: 7 },
    summary: "每队都交手一次，以胜场和回合分决定最终排名。",
    matchCount: 3,
  },
  {
    id: "king-of-the-hill",
    name: "擂台守关",
    teamCount: 3,
    minMinutes: 70,
    maxMinutes: 120,
    fairness: 7,
    fun: 10,
    seriousnessFit: { serious: 5, balanced: 8, fun: 10 },
    summary: "擂主留场，挑战者轮番上阵，适合整活和高情绪值夜晚。",
    matchCount: 4,
  },
  {
    id: "points-sprint",
    name: "积分冲刺",
    teamCount: 3,
    minMinutes: 45,
    maxMinutes: 75,
    fairness: 7,
    fun: 9,
    seriousnessFit: { serious: 4, balanced: 8, fun: 10 },
    summary: "短模式积分赛，效率高，适合时间紧但希望多队都能上场。",
    matchCount: 3,
  },
  {
    id: "dual-bracket-finals",
    name: "双半区总决赛",
    teamCount: 4,
    minMinutes: 100,
    maxMinutes: 180,
    fairness: 9,
    fun: 8,
    seriousnessFit: { serious: 9, balanced: 9, fun: 7 },
    summary: "四队开幕战后进入胜者路线和总决赛，兼顾观赏与赛制完整度。",
    matchCount: 4,
  },
  {
    id: "league-round-robin",
    name: "四队积分赛",
    teamCount: 4,
    minMinutes: 120,
    maxMinutes: 210,
    fairness: 10,
    fun: 7,
    seriousnessFit: { serious: 8, balanced: 9, fun: 5 },
    summary: "纯公平导向的四队循环赛，适合赛季周末和较长时间窗口。",
    matchCount: 6,
  },
  {
    id: "carnival-night",
    name: "娱乐嘉年华",
    teamCount: 4,
    minMinutes: 120,
    maxMinutes: 240,
    fairness: 7,
    fun: 10,
    seriousnessFit: { serious: 4, balanced: 8, fun: 10 },
    summary: "标准对局、挑战卡和全明星表演赛混搭，气氛第一。",
    matchCount: 5,
  },
];
